version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - app

  db:
    image: postgres:16
    container_name: lifehub-postgres
    restart: always
    environment:
      POSTGRES_DB: life-hub
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
