version: '3.8'

services:

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    volumes:
      - .:/app/frontend
    expose:
      - "9000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "20080:80"
    volumes:
      - .:/app/frontend
    depends_on:
      - php-fpm
